<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Web Interview</name>
   <tag></tag>
   <elementGuidId>d1ee602d-d43b-49bb-b615-eb3e11bb5c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-652 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='${interviewType}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2a5238c-0332-4943-a155-7aae9bb779af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>50957ccd-2f48-463e-9ca8-16dad685648c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Web Interview </value>
      <webElementGuid>34947e75-3457-40b8-8b79-c13919cae8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-652&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>35ab2bb1-7d7b-429b-be25-c4d5b7448ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-652']/span</value>
      <webElementGuid>7e91287c-62de-4faf-8f12-2b59c501931f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Interview'])[2]/following::span[1]</value>
      <webElementGuid>04066484-2b3b-4949-a643-3fe982e7ce07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::span[2]</value>
      <webElementGuid>84f1a76c-73f4-43bc-b209-6637ec9e066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Interview'])[1]/preceding::span[1]</value>
      <webElementGuid>b31fe5d6-1e47-4e77-b133-c27001329b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[2]</value>
      <webElementGuid>63ffffad-b9a8-4c3c-88a0-20f7e88410e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web Interview']/parent::*</value>
      <webElementGuid>901b1540-bb3a-44e3-aa1f-a72f3ee369dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>1deb0f0d-1e11-4f05-99f9-05b41797f855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Web Interview ' or . = ' Web Interview ')]</value>
      <webElementGuid>fa7669bc-2dbb-442b-b56d-70a13ace744b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
