<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IT</name>
   <tag></tag>
   <elementGuidId>5ba7c295-fb65-4ff8-8b16-15cb5fb18095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/mat-select/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-191</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>834cac22-d2bf-4840-aa06-15760f2b6978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-110</value>
      <webElementGuid>fdc40e22-987a-4403-b32b-cd4474d82adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-191</value>
      <webElementGuid>4dd3f876-a636-46be-bb3d-e830628cd243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IT</value>
      <webElementGuid>86bfc383-b2cf-45af-952a-e7f533e24863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-191&quot;)</value>
      <webElementGuid>07800734-2342-4621-920a-069df87ff9e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-191']</value>
      <webElementGuid>0c5ffe0b-ed82-40e2-be23-6bc2a5dcaa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//mat-select[@id='industry']/div/div)[3]</value>
      <webElementGuid>099bb5f3-3504-465c-96bb-4f541371a06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ii. Industry'])[1]/following::div[3]</value>
      <webElementGuid>8c70d448-d9b5-4e91-a8b8-ff685224efc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i. Location'])[1]/following::div[5]</value>
      <webElementGuid>1eb79ef5-de23-4c70-aefc-8fe2ffd2cd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iii. Keyword'])[1]/preceding::div[3]</value>
      <webElementGuid>8a48d42d-2661-4f4c-9974-cf5849bb9345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/mat-select/div/div</value>
      <webElementGuid>2f3d91dd-8676-4df8-a106-2389d5590ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-191' and (text() = 'IT' or . = 'IT')]</value>
      <webElementGuid>127e6bc8-cf2a-4a10-8ee0-87034ad00885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
