<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_No Data Found</name>
   <tag></tag>
   <elementGuidId>9b3a17c7-6f88-4deb-bfaf-6cf087d1432c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search_candidates']/app-vacancies-search-candidates/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>dda36166-b429-4428-89a4-e1de22b876a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>1f9147f9-dec9-4c44-bb8a-6e0c6bd4a586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Data Found</value>
      <webElementGuid>2aa5f558-3c11-415c-a120-9c48cf58f6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTabContent&quot;)/div[@id=&quot;search_candidates&quot;]/app-vacancies-search-candidates[@class=&quot;ng-star-inserted&quot;]/h4[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>c143e38d-95d8-4e33-af5f-683eda2a954a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_candidates']/app-vacancies-search-candidates/h4</value>
      <webElementGuid>cd930edf-4cbc-4402-b680-932ed6f3f5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::h4[1]</value>
      <webElementGuid>2f66912d-edc2-4d3b-bcc3-98c41b59e487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::h4[1]</value>
      <webElementGuid>abd8d857-9674-46b1-bc83-23c8d4092e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Ginger'])[1]/preceding::h4[1]</value>
      <webElementGuid>edc645d8-9c15-408b-b17f-55c287b7eed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>4859dc46-94cd-495c-8f76-41f879f9775a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'No Data Found' or . = 'No Data Found')]</value>
      <webElementGuid>0c6c7504-6263-4a0c-8383-ee70d488e858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
