<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cancel_dont_ask_flg</name>
   <tag></tag>
   <elementGuidId>1961c791-c156-4364-acec-25bf232cd25c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dont_ask_flg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dont_ask_flg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4956f47-fbb4-42c3-8b5a-a4b9b7b4761e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>829e797f-5307-4ee6-be98-62a844a77c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dont_ask_flg</value>
      <webElementGuid>8e6c1b1c-4bc0-47ae-b9b9-4bf8041facaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dont_ask_flg</value>
      <webElementGuid>2efa4fac-c476-425e-b29d-fc7d9788e853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dont_ask_flg</value>
      <webElementGuid>d4bc1013-10c6-4a13-bb5c-8d0c7e1aa34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a496b888-39e9-4fe0-8342-64fc48af9d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dont_ask_flg&quot;)</value>
      <webElementGuid>8103047d-3380-4555-93f0-d9850555866e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dont_ask_flg']</value>
      <webElementGuid>cef80dd9-c189-49ed-a664-a2f6b5bc8a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3ce31628-0817-4ab6-9f8a-e90643fa18b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'dont_ask_flg' and @id = 'dont_ask_flg']</value>
      <webElementGuid>31b1d7b1-0c7b-420f-a552-306c6391fc27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
