<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Appointments</name>
   <tag></tag>
   <elementGuidId>1bc2545a-d4e0-4788-a282-b8251af7aabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='appointments-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appointments-tab</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'appointments-tab' and @type = 'button' and (text() = ' Appointments ' or . = ' Appointments ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f180966e-d32f-49ed-a984-8b62c03c1a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appointments-tab</value>
      <webElementGuid>40a3b81e-6ac2-4f52-90b5-bff278bb0ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4244c2cf-d2b7-4614-841d-9389b1c76839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#appointments</value>
      <webElementGuid>e37fc78d-100f-455a-8d61-fe1d5d0d47c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7af8b3d8-a369-4258-bf9d-b7c9d8fecbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-link-custom active</value>
      <webElementGuid>83859398-22f2-4388-a906-7d3dc209ce87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Appointments </value>
      <webElementGuid>b5b8cb63-c8d9-4329-bcb5-d55339294a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appointments-tab&quot;)</value>
      <webElementGuid>c515584f-23f6-4cb0-af9b-bb2b325d6151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='appointments-tab']</value>
      <webElementGuid>4ef32933-48f5-42b4-8856-27f07beaf471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[3]/button</value>
      <webElementGuid>1cd657d2-e945-4dc7-8d2d-b3518471bd12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicants'])[1]/following::button[1]</value>
      <webElementGuid>dee00a5f-4176-4b47-bcc0-50e42823560d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job description'])[1]/following::button[2]</value>
      <webElementGuid>ec48768d-b267-49a2-8443-257002dfd1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of suggested candidates'])[1]/preceding::button[1]</value>
      <webElementGuid>daa8a722-78a2-4110-9e40-c0bedec2f992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search candidates'])[1]/preceding::button[2]</value>
      <webElementGuid>0cf43eaa-7f84-4434-ba44-c84e933e5a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Appointments']/parent::*</value>
      <webElementGuid>e2c90829-8e01-4b15-b920-2bef1dbb5e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>6669af85-9ff0-4c7f-a076-e1e0cc939bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'appointments-tab' and @type = 'button' and (text() = ' Appointments ' or . = ' Appointments ')]</value>
      <webElementGuid>a85beb64-16f1-4ecd-ae1a-acdebcc83b7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
