<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_quaildecoygmail.com_download-img</name>
   <tag></tag>
   <elementGuidId>124371fb-a010-44e0-9aa6-7c6f795719cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseOne']/div/div/table/tbody/tr[2]/td[5]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.download-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5477617e-9d38-4503-b68b-91ff7b7a4839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/download.png</value>
      <webElementGuid>c910d360-3024-4f4a-ba80-dd56c3fac083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>ff8efafd-5591-4e4e-ae8e-bbf9eae9607b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>download-img</value>
      <webElementGuid>f3b5d16f-b483-4fbb-a4f5-ff2bdfdfee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicants&quot;)/app-vacancies-applicants[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;job-ab-content ng-star-inserted&quot;]/div[@id=&quot;accordionExample&quot;]/div[@class=&quot;accordion-item job-accordion border-0&quot;]/div[@id=&quot;collapseOne&quot;]/div[@class=&quot;accordion-body p-0 job-accordion-body&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-applicants text-center font-14&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-inline-block&quot;]/img[@class=&quot;download-img&quot;]</value>
      <webElementGuid>8abef0ee-1c50-4352-b4fa-322df5c4db0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div/table/tbody/tr[2]/td[5]/a/img</value>
      <webElementGuid>afea0d85-fb07-458c-a879-d48ce050b6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Download']</value>
      <webElementGuid>02a52b8d-c4cf-45c8-ba3e-e6490fc1ad90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/img</value>
      <webElementGuid>72038aff-1dbf-4335-a1df-aa6433dced5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/download.png' and @alt = 'Download']</value>
      <webElementGuid>f64a0a76-e12f-4e23-b248-57131be930bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
