<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Salary Type</name>
   <tag></tag>
   <elementGuidId>fbedf369-131e-4a38-a923-7512557f7caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-93</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mat-select-value-93' and (text() = 'Select' or . = 'Select')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='salary_type']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f38e076-23ef-4c28-a52b-362db0b9286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-50</value>
      <webElementGuid>56156448-42be-4f20-af03-1b815858d616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-93</value>
      <webElementGuid>ffa7347d-d390-486f-a1b0-5fc2207021e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>730bca37-a374-4b59-9c96-89b98c26a7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-93&quot;)</value>
      <webElementGuid>f22d413c-ffe3-418f-80f2-1272070bb36b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-93']</value>
      <webElementGuid>1dd1d2f4-e67a-4e8b-a005-6bc683bfd44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='salary_type']/div/div</value>
      <webElementGuid>5e82de3f-cc13-4460-9f4c-e08dab0d226a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary Type'])[1]/following::div[3]</value>
      <webElementGuid>3168ee9b-3b73-487a-a8d7-1b91cf8e7aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To salary'])[1]/following::div[4]</value>
      <webElementGuid>4bea14e1-0e12-4bb5-b568-556d9841c21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status*'])[1]/preceding::div[3]</value>
      <webElementGuid>1cf054a7-2d46-476e-93a0-db69840a2341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>f42f471d-90b0-4373-942c-eb18a5547683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-93' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>cc309a52-581b-46aa-aa4f-536c8ae93788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
