<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country Location</name>
   <tag></tag>
   <elementGuidId>2f2357f9-e578-4ca4-b3bf-05abf1ddb6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-95</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'mat-select-value-95' and (text() = 'Country' or . = 'Country')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e19c4bf8-9f63-4229-9f52-50e1b60b301d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-51</value>
      <webElementGuid>8fec37f2-eeea-4022-b876-68e7b7e22efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-95</value>
      <webElementGuid>5faa5df2-6717-40d0-a1d9-6de1ebe95b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country</value>
      <webElementGuid>c069d117-bd57-4830-9661-4147b0fe82d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-95&quot;)</value>
      <webElementGuid>7767144b-d5ba-49ea-b73d-1eb94d99db53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-95']</value>
      <webElementGuid>01ace1b1-cb33-4cc5-ad79-4ad7fe03f2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='country']/div/div</value>
      <webElementGuid>aed68371-093a-475d-9fba-476b3935fbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location*'])[1]/following::div[5]</value>
      <webElementGuid>63c09a40-0f22-4bd7-bb13-2e8d2fa28e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[6]</value>
      <webElementGuid>24ace1f9-c331-406b-9f9a-e257eadc31aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/preceding::div[3]</value>
      <webElementGuid>f37982b3-aa3c-4455-80dd-28a66d20f38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/mat-select/div/div</value>
      <webElementGuid>bc9db075-f2c4-4c13-93ce-bf9c9cbfcf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-95' and (text() = 'Country' or . = 'Country')]</value>
      <webElementGuid>293de283-7eb3-43d5-bcfc-0ec8647d753d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
