<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Education Industries</name>
   <tag></tag>
   <elementGuidId>8360d2f4-0b67-4c88-a306-5b07b681f0a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='technology']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e46326a7-d4bb-4b67-b35b-1c7afbf10c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-54</value>
      <webElementGuid>7753d7bd-a2a8-4854-9620-039bc8a694a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-101</value>
      <webElementGuid>76aef981-ca2c-4e99-aa36-fd69170e73f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>99b51d14-648a-47ea-a2cb-1ebc877b80ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-101&quot;)</value>
      <webElementGuid>ce3babd6-ebce-43ef-9e09-ced6f1eef6ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-101']</value>
      <webElementGuid>cad89cb8-640a-4151-8e9b-dca4f75aa77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='technology']/div/div</value>
      <webElementGuid>e1b3291f-8689-4524-bb1e-c90251554d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industries*'])[1]/following::div[5]</value>
      <webElementGuid>54f80f1f-dc03-465a-92c9-8cae7f5a20fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/following::div[6]</value>
      <webElementGuid>8a40adf5-cf4d-4b41-a6d6-6319c5508dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Candidates', &quot;'&quot;, ' Citizenship*')])[1]/preceding::div[3]</value>
      <webElementGuid>39ae999c-265c-4d3c-a95f-13fb0caa4c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/mat-select/div/div</value>
      <webElementGuid>f22c7b88-e8fe-4b9f-b850-88aed0d32249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-101' and (text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>3533ad63-5961-4578-96d5-4b5e81069019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
