<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_status</name>
   <tag></tag>
   <elementGuidId>eb72172e-6d74-46de-a902-c214701898a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'status' and @id = 'status2']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56bac2c4-cc62-4442-a24c-adeabc1bd149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>be0fec4b-b107-49ca-85b6-6252cfadb8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>6304c611-7231-41e6-9987-1d0c440572c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>3dfb5476-04d2-49a4-af5f-8baaca455ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status2</value>
      <webElementGuid>3564e75f-9219-4c61-a950-31f4a5bd13e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d7637b2-6753-4076-b371-ddc0d6fbd751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input ng-dirty ng-valid ng-touched</value>
      <webElementGuid>b7eba952-785c-4c3b-afb9-4b724320b304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status2&quot;)</value>
      <webElementGuid>820afdf8-e2d6-44be-98c7-b2f67e273857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status2']</value>
      <webElementGuid>7d30bb3d-15ab-426c-b969-e14f7ff99f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/input</value>
      <webElementGuid>4ee7d860-7598-4911-a4f6-e7d50567915b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'status' and @id = 'status2']</value>
      <webElementGuid>a35d50cf-be34-47c4-9e50-3cb53d8ee7a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
