<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job End Date_job_end_date</name>
   <tag></tag>
   <elementGuidId>92fffe5d-d1b4-471a-a79f-b3459320d4fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b815a573-1f73-4719-ba55-bf6766574410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>70dbe3c4-41b1-450e-92af-529627b30ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>job_end_date</value>
      <webElementGuid>cec4af59-2211-407b-b6f9-ec844073e0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_end_date</value>
      <webElementGuid>bce1d26f-90a1-4aac-89d4-0e797b318bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_end_date</value>
      <webElementGuid>3485747f-fef9-4e91-9c51-6537de3561ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control job-date-input datepicker ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>99873905-e7a2-4efb-9a9e-11b85f8db56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2024-02-02</value>
      <webElementGuid>69c55651-c3bd-410b-94a0-be880d0bf867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_end_date&quot;)</value>
      <webElementGuid>ea470048-86e3-4fa4-b3a6-208169fd8f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_end_date']</value>
      <webElementGuid>e4307087-b2a4-43bd-8e04-a62c81745406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9d8215fc-40e1-4c20-b3c6-d819ff0ada04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'job_end_date' and @name = 'job_end_date']</value>
      <webElementGuid>a8528eba-df01-49cf-a66e-e19acf7e5bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
