<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_c) Job Highlights_job_highlights</name>
   <tag></tag>
   <elementGuidId>aef1b24c-594c-4e3b-abc6-63de47731de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;job_highlights&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='job_highlights']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1be97379-716f-481f-b795-7fade0283d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62f67531-119b-4349-b279-f6f1984a1804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>job_highlights</value>
      <webElementGuid>9f01c5c7-66f3-4fad-92ac-cd1aef22b874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_highlights</value>
      <webElementGuid>4fb26b82-0a5a-4493-8dc3-a0951751c706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>responsiblities-input form-control mb-3 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8c8fd6d2-2755-49ea-969b-f3c50b0eebda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-job-posting[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;job-posting-page&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-md-8&quot;]/div[@class=&quot;posting-form&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 posting-col&quot;]/div[@class=&quot;label-part mt-0 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;input-position position-relative ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/input[@class=&quot;responsiblities-input form-control mb-3 ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>e055bf7c-25d1-496a-aca1-15f6e81ab944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='job_highlights']</value>
      <webElementGuid>ab68fed0-eabb-4ad3-94ea-6f26559e3597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[3]/div/input</value>
      <webElementGuid>84d78fbd-40dd-48a6-a0e5-d7c04c56276c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'job_highlights']</value>
      <webElementGuid>b1ca02e6-8731-419b-a2a6-1e18f5cd79f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
