<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vacancy Title_vacancy_title</name>
   <tag></tag>
   <elementGuidId>d1fba5fa-3f0b-423b-88c0-6fe90684ce9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vacancy_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vacancy_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6342e6c-d809-4eaf-8cc3-01f2eb288d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14e88965-11c5-4820-957e-53965c7bb62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>vacancy_title</value>
      <webElementGuid>ca9f5ef9-5381-4846-b8c6-bc436aa98ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vacancy_title</value>
      <webElementGuid>cb2af896-2675-43b1-a84c-6ef706150db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vacancy_title</value>
      <webElementGuid>cb8385ca-b8b6-44b2-848e-11d910d33b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-input-custom focus-remove ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ff8ce3ad-a6c2-46b2-bdd3-597d3f69d3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vacancy_title&quot;)</value>
      <webElementGuid>8bfbba3e-ddc6-4c10-8b33-3a52aceb0d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vacancy_title']</value>
      <webElementGuid>59b46b0b-9864-4169-9be7-0005387af4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>20e382e9-5d04-4279-acc0-63d783b8d78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'vacancy_title' and @name = 'vacancy_title']</value>
      <webElementGuid>0ea1d9e5-28ee-4d37-83f4-edf7b3b0768b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
