<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Citizenship</name>
   <tag></tag>
   <elementGuidId>55a83829-0373-4cab-a207-afdcfe022de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#citizenship1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='citizenship1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28d5f3ec-a568-46e8-b168-6424a96f7eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>90af45dd-e2e4-41eb-86bd-7416d42aecb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>citizenship</value>
      <webElementGuid>813428b3-7e12-4027-9e37-0ccae8827938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>citizenship</value>
      <webElementGuid>fed19908-906d-4a0e-8f59-41eee5e0595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>citizenship1</value>
      <webElementGuid>e1b974e5-c2c5-4510-b2ab-694aac07b735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Malaysian</value>
      <webElementGuid>a921ec4d-87d8-4b3a-a09b-89b17dc9132e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>87ab03c1-7642-4947-a8e9-1bd5d1aa8a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;citizenship1&quot;)</value>
      <webElementGuid>3142814b-c52f-4b23-a5dc-792c149ee093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='citizenship1']</value>
      <webElementGuid>da2e20b7-bdf3-4df5-abf6-01bf3d3cdce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>84cb258b-bf77-471a-9658-76efb5afa71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'citizenship' and @id = 'citizenship1']</value>
      <webElementGuid>020b436c-3313-45d9-a93d-636061f06823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
