<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Applicants</name>
   <tag></tag>
   <elementGuidId>462dc120-86dd-4dd3-a0af-f9a7e31d587e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applicants-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aebbc201-9fbc-4c9e-9f76-62dbbd9269f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applicants-tab</value>
      <webElementGuid>07751d9a-37d2-48db-a4ad-f75da94adf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4505b779-623b-4f9d-9f69-06b6b002f342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#applicants</value>
      <webElementGuid>6239ad6f-1213-4b7d-8215-7073fb799df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a02d3e1d-5789-452c-b86d-b798b17ee608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-link-custom</value>
      <webElementGuid>3e74e338-f220-4539-bdff-3c0805c98d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Applicants </value>
      <webElementGuid>c542faeb-db63-4e0b-85d0-a1cfff3432fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicants-tab&quot;)</value>
      <webElementGuid>8cfc25e8-bc3e-4249-907b-7568a70b8fd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='applicants-tab']</value>
      <webElementGuid>ae741791-225d-47d5-8c17-f37e74ad1c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[2]/button</value>
      <webElementGuid>4a477f12-be7d-4f3e-bb1a-981703dffb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job description'])[1]/following::button[1]</value>
      <webElementGuid>951d7a72-ec38-4e2b-aa8a-8f3349f85e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/following::button[2]</value>
      <webElementGuid>47f3109b-4bbf-410e-9f79-3fc8372dd6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointments'])[1]/preceding::button[1]</value>
      <webElementGuid>2d7c6497-aa59-4c71-b18c-707198d97fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of suggested candidates'])[1]/preceding::button[2]</value>
      <webElementGuid>5d8374a7-6f29-4d2d-a426-7942ea708987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Applicants']/parent::*</value>
      <webElementGuid>1f19750d-6662-4933-a880-a8c48b2bd127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>4dc20998-7105-49e3-8977-43e4c250c5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'applicants-tab' and @type = 'button' and (text() = ' Applicants ' or . = ' Applicants ')]</value>
      <webElementGuid>a784c0d6-edb1-4660-85c8-da1e215cfe8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
