<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_X_hired_candidates</name>
   <tag></tag>
   <elementGuidId>3f14b8fd-ed2b-4ca0-bcb8-fa980d0f81cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hired_candidates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hired_candidates']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8f18cf3-6c6c-4475-a64e-95faff9f825b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2d15881-cd78-42ad-99b2-aa2a6c13db01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>hired_candidates</value>
      <webElementGuid>8e1f7c47-5af6-4dba-b7bb-f47030f18514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hired_candidates</value>
      <webElementGuid>86c4c250-4074-45e1-a91b-3c8bdd81dd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hired_candidates</value>
      <webElementGuid>2538ca92-7daf-46cd-8084-c36e148bdb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number</value>
      <webElementGuid>bf50a3e8-ba5c-405a-baf6-7520263a7e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cbe2007b-6bc8-4a95-bf2f-e6375111d4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hired_candidates&quot;)</value>
      <webElementGuid>fbb79a3a-8594-4959-9289-a9683c83bf66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hired_candidates']</value>
      <webElementGuid>01a6c995-9c1a-454c-b154-fe46e5bc693c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div/div/input</value>
      <webElementGuid>36f8bbfb-87c8-4311-a640-1c6dc1877607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hired_candidates' and @id = 'hired_candidates' and @placeholder = 'Number']</value>
      <webElementGuid>c7ed40cd-2558-459f-b96e-587ac540f2f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
