<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BCA Qualification</name>
   <tag></tag>
   <elementGuidId>85cdfc3d-0f1b-408e-8881-ae16a9199051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-103</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='qualification']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3cb406e-257a-4e2d-881a-c29cfe51cfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-55</value>
      <webElementGuid>a8254527-3912-4a12-a028-0006f51d1533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-103</value>
      <webElementGuid>9fa3d017-faa5-4f21-a32a-4db3c4f8f1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCA</value>
      <webElementGuid>9ff17d85-7af0-4e66-8d54-811d14e69138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-103&quot;)</value>
      <webElementGuid>b452b2b8-607d-4822-ac76-35ae6c656e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-103']</value>
      <webElementGuid>2fa23924-1994-469b-84f3-5963f84837a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='qualification']/div/div</value>
      <webElementGuid>01f20505-5109-41cb-8044-0b74bf7da40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a) Qualification'])[1]/following::div[3]</value>
      <webElementGuid>f5d35bdb-7bef-4fec-a069-af4e4491fafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About the Candidates*'])[1]/following::div[4]</value>
      <webElementGuid>505e37ae-660d-4daa-84dc-62b8a7fbe3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='b) Experiences'])[1]/preceding::div[3]</value>
      <webElementGuid>68682dcc-0878-4411-918b-c21f7ae65ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/mat-select/div/div</value>
      <webElementGuid>1b3a853d-77f8-4e2b-872a-28a872501f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-103' and (text() = 'BCA' or . = 'BCA')]</value>
      <webElementGuid>80759c9c-8dd4-4428-b344-32e534f1dc76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
