<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_City  Location List</name>
   <tag></tag>
   <elementGuidId>0c7dbb5d-7d02-4dfe-a378-079c82e2d424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-99</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='city']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2329a03-185f-408e-b447-c3324c071316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-53</value>
      <webElementGuid>438560c8-1723-44ea-a2fe-69ea1e032d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-99</value>
      <webElementGuid>690c95db-b1a4-4b0f-8457-920e41e9901c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>18e3d165-1750-4285-a82e-e9c1aa499981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-99&quot;)</value>
      <webElementGuid>bf70df60-edb3-4cb2-84ed-6b7b53324027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-99']</value>
      <webElementGuid>bb8b3074-3f43-4684-98d3-11e66a08033a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='city']/div/div</value>
      <webElementGuid>25887113-dd09-4c8a-956a-811d081a85f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::div[6]</value>
      <webElementGuid>2cc647ac-3f91-4788-8bb5-71f72be5686d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thailand'])[1]/following::div[12]</value>
      <webElementGuid>308e9474-fed6-40b9-b796-f08ccbe54f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract Type*'])[1]/preceding::div[3]</value>
      <webElementGuid>1e5482e2-7cc8-485a-8e98-c859094a39b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/mat-select/div/div</value>
      <webElementGuid>caca799d-fee1-4c95-bd59-0772a58d7d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-99' and (text() = 'City' or . = 'City')]</value>
      <webElementGuid>bf6c1d5d-c983-4f4b-9378-b92da27a66dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
