<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Start Date_job_start_date</name>
   <tag></tag>
   <elementGuidId>53b0bad7-d199-4613-a9ed-c3093e8fd82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_start_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_start_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0ea970b-f282-4a5a-893e-db8799e04d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8e481fe8-5133-4b1f-b259-270309eb2fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>job_start_date</value>
      <webElementGuid>68fa9e23-94b2-4e46-9271-207af71770af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_start_date</value>
      <webElementGuid>58a410f3-7ba9-4bbd-9e12-d61b22215d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_start_date</value>
      <webElementGuid>978dc859-1c9c-4296-af80-b0afa34a5f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control job-date-input datepicker ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>56f05e15-d0b1-4147-ac88-269a48440fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_start_date&quot;)</value>
      <webElementGuid>cd982f85-8ce2-4cfd-8e91-5cce737d0531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_start_date']</value>
      <webElementGuid>73f160c2-73e6-4999-9a74-c57639fe7b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>e0041dd5-a667-469b-a803-c477e51e177e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'job_start_date' and @name = 'job_start_date']</value>
      <webElementGuid>01df9868-5c6b-4d5a-bd96-dd392c567d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
