<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b) Responsibilities_responsiblities</name>
   <tag></tag>
   <elementGuidId>858ab422-be08-42c3-b979-f4d8e989d870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='responsiblities']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87482c36-21be-4314-8110-d7c9b8811e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11218cdc-93aa-4b96-840a-553fbb343b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>responsiblities</value>
      <webElementGuid>4670e387-16b0-49a6-9d62-114bd99d8dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>responsiblities</value>
      <webElementGuid>36330879-a957-4036-9fd1-7bc615fd4570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>responsiblities-input form-control mb-3 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c4e2d3d9-8b3a-41ec-9ac3-d4f64c31e4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-job-posting[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;job-posting-page&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-md-8&quot;]/div[@class=&quot;posting-form&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 posting-col&quot;]/div[@class=&quot;label-part ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;input-position position-relative ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/input[@class=&quot;responsiblities-input form-control mb-3 ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>d2280578-c78e-48a0-98fa-76ae77a7a5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='responsiblities']</value>
      <webElementGuid>f88fc183-a923-405a-9dae-a0d8e26a4127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/input</value>
      <webElementGuid>10e60c1d-0464-4ee3-a909-78253e7cdec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'responsiblities']</value>
      <webElementGuid>d7eea293-c800-4c63-a2a9-1bc788b989c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
