<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visa Support</name>
   <tag></tag>
   <elementGuidId>671d4833-a029-4de5-ac2f-584e84b443b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visa1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='visa1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8525fb1-12a9-4213-a546-9f322aa6d848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2f874f10-84dc-42e2-ae16-41dd705b684e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>is_visa_support</value>
      <webElementGuid>c87892d5-bb43-4d57-918e-6441e74b7547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_visa_support</value>
      <webElementGuid>bd69aa72-8793-482c-826d-1eafa8a6d399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visa1</value>
      <webElementGuid>29c6fe2a-5739-4a8b-96eb-1b744cd79c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>65454a04-849f-4832-8462-c70e8152c836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>f616ff1b-d46a-4545-95ec-7270863055e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visa1&quot;)</value>
      <webElementGuid>55b27baf-8398-496d-8f96-47872b4deb9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='visa1']</value>
      <webElementGuid>4a304dd7-759a-45f8-905a-1a01b3aa4b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>e3a54853-549f-466f-b43b-84bbe2721abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'is_visa_support' and @id = 'visa1']</value>
      <webElementGuid>323df328-f241-462e-8669-f805e3c6b2b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
