<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visa Support</name>
   <tag></tag>
   <elementGuidId>671d4833-a029-4de5-ac2f-584e84b443b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visa1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='${visaSupportIs}'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b03b63c2-a3c1-47a4-85f4-776c2ef85b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3ab36d82-e72a-4b9e-8f7e-42ddc0aadfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>is_visa_support</value>
      <webElementGuid>c9e89233-1bd8-444d-be9a-cfa807a094a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_visa_support</value>
      <webElementGuid>ca3dcc5b-108f-47dc-af1c-95e8780b39f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visa1</value>
      <webElementGuid>fd70b138-ed16-4171-811d-143ea194fbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b33e0af4-f45a-4a2b-856b-b7b8ae3c4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>437ea22c-f959-4be0-85f7-5975be9aabc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visa1&quot;)</value>
      <webElementGuid>63584a17-b419-49a4-b042-4659b4fead3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='visa1']</value>
      <webElementGuid>79129839-8357-4ef1-8d4c-2dd208a61b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>c8a9b94f-7e6a-4c26-b0ab-66b833ba3a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'is_visa_support' and @id = 'visa1']</value>
      <webElementGuid>4946f372-e47a-4803-93fd-dc2424b02596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
