<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Malaysia</name>
   <tag></tag>
   <elementGuidId>617779b0-b5a4-4d4e-8fee-97970beb3c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-1510</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id = 'mat-option-1510' and (text() = ' ${country} ' or . = ' ${country} ')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${country}' or . = '${country}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>6644cefb-9186-4431-ab69-a88f9a9545e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b44aa16c-e434-4749-ac87-5a467e1df74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-tns-c49-90 ng-star-inserted mat-selected mat-active</value>
      <webElementGuid>02631d2a-185e-45b2-885e-e4b3362e92fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-1510</value>
      <webElementGuid>45dbeb28-b1dc-426f-9cf2-c8ff3aac50b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ab8ff4b-3d64-4ffb-a068-085a2607ea4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>80702ae1-faa3-4641-b9a1-58f7db9bd7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66697c38-e07b-41b3-944a-da9bc9879693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${country}</value>
      <webElementGuid>82b5e84e-498f-451c-b9ca-5e8db86bda08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-1510&quot;)</value>
      <webElementGuid>cf933566-23f7-4ea2-ab4c-a3a09dc82140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-1510']</value>
      <webElementGuid>2214f380-6297-425e-8c3e-5bf1c3961c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='country-panel']/mat-option[4]</value>
      <webElementGuid>f206248c-7ce9-4bf7-bd99-258d0aa0715a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::mat-option[1]</value>
      <webElementGuid>3e5a59d1-9147-4a0f-aae6-2590ce544a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/following::mat-option[2]</value>
      <webElementGuid>27ac5fad-6474-4124-bc97-c0064bb71fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>a10f2547-476d-41f1-a698-7538d53823c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[4]</value>
      <webElementGuid>f313be03-b5f7-46a1-b448-09a47bce8198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-1510' and (text() = ' Malaysia ' or . = ' Malaysia ')]</value>
      <webElementGuid>79bbcc0d-08b9-4e26-bfc1-7e916bdd54f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
