<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From salary_from_salary</name>
   <tag></tag>
   <elementGuidId>64944de1-4e1c-4944-a4c7-5c5603a956ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from_salary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from_salary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20db1392-a590-44bd-ac8b-7aefcce7ccb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9271e33-8cf3-4be1-a559-069ff1a07147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+[.,]?[0-9]*</value>
      <webElementGuid>a70d180c-1985-4f91-b761-e353285309d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>from_salary</value>
      <webElementGuid>bb5c504d-8268-4da3-846f-fa1f596ae09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from_salary</value>
      <webElementGuid>3e7b13a6-11a8-4ea3-b1b1-d34a09e97518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>from_salary</value>
      <webElementGuid>54e7a042-626b-44d4-b06f-ec0e20e46607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control description-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>250acf9b-9fcc-4fcb-b680-9aa97548fa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from_salary&quot;)</value>
      <webElementGuid>44dc3218-828c-4fc9-b782-8d45e837f835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from_salary']</value>
      <webElementGuid>24c584d4-b8ac-480e-9a02-eac6d2adec28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/input</value>
      <webElementGuid>64c76ecf-cd06-4fd1-a4b9-ec41fcb5b9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from_salary' and @name = 'from_salary']</value>
      <webElementGuid>36a28c9d-fb45-4969-b4b3-18ac958c9feb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
