<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contract Type_engagement_type</name>
   <tag></tag>
   <elementGuidId>3f88c9c6-8520-4530-9f95-fdaa8ce56722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'engagement_type' and @id = 'engagement1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#engagement1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='engagement1'])[${contractTypeIs}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>386b08ee-05f4-4526-931d-bea9dab138bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>engagement_type</value>
      <webElementGuid>b9b143cd-e536-4dad-ac79-0f2a7b4ef5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e6fd73e0-25df-4f88-a3d3-fe2bdae81260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>engagement_type</value>
      <webElementGuid>8d20a88d-c81f-4bb5-a43d-333132873cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>engagement1</value>
      <webElementGuid>58ee11e9-0a28-450e-9d94-1820a3dbf5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>92b3704a-380b-4a6d-b196-76ec7aca2cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-job-posting[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;job-posting-page&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-md-8&quot;]/div[@class=&quot;posting-form&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 posting-col&quot;]/div[@class=&quot;radio-flex d-flex&quot;]/div[@class=&quot;radio-grid ng-star-inserted&quot;]/div[@class=&quot;form-check custom-form-check position-relative&quot;]/input[@id=&quot;engagement1&quot;]</value>
      <webElementGuid>8a95c1f0-d3c8-4a71-bb49-9644fa0825a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='engagement1']</value>
      <webElementGuid>5ad9b0f8-f5ce-4e32-9906-7d698acd742d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>72570279-eaea-463d-a684-45e229bf00df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'engagement_type' and @id = 'engagement1']</value>
      <webElementGuid>c03d943a-2f4f-4347-a2f5-5f18c42ee9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
