<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Citizenship</name>
   <tag></tag>
   <elementGuidId>55a83829-0373-4cab-a207-afdcfe022de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#citizenship1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='${citizenshipIs}'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3773ed4e-ddb4-40f3-aa2d-c7c34c018c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b77f296c-1f7a-447e-aa6a-4ae48d1dbb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>citizenship</value>
      <webElementGuid>045c4963-0730-4ac7-8f08-b895d032cd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>citizenship</value>
      <webElementGuid>2edb2f3f-5514-4cd2-b53a-b258e7a00b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>citizenship1</value>
      <webElementGuid>02a53280-cda7-458a-9ecd-60e0412e0da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Malaysian</value>
      <webElementGuid>a19be529-5750-4b38-8e6f-c7bf24a56287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input custom-check-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>c87a1505-5c39-46cc-a4c4-cce90025a9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;citizenship1&quot;)</value>
      <webElementGuid>b5f345dd-fa70-4269-bd39-9377069eee17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='citizenship1']</value>
      <webElementGuid>4906d677-38e1-4dbb-ade5-5dcfb7aa1d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>ad72f9cb-8692-42e3-af7b-d5153a2c23b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'citizenship' and @id = 'citizenship1']</value>
      <webElementGuid>212c8730-91e9-43f2-8ee7-fa5430c19f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
