<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_c) Skill Sets_skillsets</name>
   <tag></tag>
   <elementGuidId>75f78d54-36ab-4655-9864-10730a809cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skillsets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='skillsets']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d7eac06f-015e-4a32-a822-5ed4eb11b45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skillsets</value>
      <webElementGuid>5cc0c7af-27dd-41af-a149-83efdc9df65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>skillsets</value>
      <webElementGuid>14647f65-e1f6-47b1-b7e2-99749eb75584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skillsets</value>
      <webElementGuid>850768e3-7e93-417f-aea1-eb4b477e9ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>description-text form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>56d48708-ac98-484c-84fe-374a18385e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>768bc12c-e59c-45e3-86fe-031d117b6a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skillsets&quot;)</value>
      <webElementGuid>031c1d0a-4f25-4fa4-a970-8a41a81995e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='skillsets']</value>
      <webElementGuid>3190be0c-c8e1-4882-9d16-e125901b0b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>27916046-a1a5-4b1a-828c-946f2ba3b9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'skillsets' and @id = 'skillsets']</value>
      <webElementGuid>dd160704-8a32-48b9-9b2b-37c8488d6f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
