<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_List of suggested candidates</name>
   <tag></tag>
   <elementGuidId>4b23b2a3-c301-4f36-93ee-bf57b9447df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#candidates-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='List of suggested candidates']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16d0dc16-c113-4208-95de-d34232889222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>candidates-tab</value>
      <webElementGuid>37e6b5b8-d6fc-4801-9340-98cd15ba7d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ef3ed46e-5709-4054-acca-fccd0688e72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#candidates</value>
      <webElementGuid>41d1ae62-dbf2-4a1a-a888-93b3c7be9a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2f32bf3-3e63-4b63-b05a-6ee162bf9b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-link-custom active</value>
      <webElementGuid>0dd7da57-0b88-46f2-bf82-8fb2f50ace7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> List of suggested candidates </value>
      <webElementGuid>d28ed491-fa2f-4480-8ca8-2a103e18f069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidates-tab&quot;)</value>
      <webElementGuid>e27f0c2c-e4c8-4d53-880e-5100310805fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='candidates-tab']</value>
      <webElementGuid>f6e6887f-f231-41f3-be4c-9357c5baa813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[4]/button</value>
      <webElementGuid>d050e04b-30c8-4d43-a0e3-70446ca0bd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointments'])[1]/following::button[1]</value>
      <webElementGuid>c34c5196-6b3c-4163-908b-0cb1433869d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicants'])[1]/following::button[2]</value>
      <webElementGuid>bc0e9c99-c4da-4654-ae83-ee8ab6b3485f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search candidates'])[1]/preceding::button[1]</value>
      <webElementGuid>6fa82135-460b-4959-807c-daf7f78a4459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information regarding the job'])[1]/preceding::button[2]</value>
      <webElementGuid>47cebf8c-d49b-4786-91af-c9e75781fdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='List of suggested candidates']/parent::*</value>
      <webElementGuid>8b159237-2859-48e6-b272-3b8c0782949b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>d73014be-7b19-4c26-a9a8-7fd046796e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'candidates-tab' and @type = 'button' and (text() = ' List of suggested candidates ' or . = ' List of suggested candidates ')]</value>
      <webElementGuid>ca233f3a-7af7-467d-92a5-13e1422c26a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
