<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Information regarding all applicants for this vacancy</name>
   <tag></tag>
   <elementGuidId>c76c2c33-be31-4d40-8c2a-74f2bb376e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search_candidates']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_candidates > h2.sub-headline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a5a18641-9132-4411-b2c5-64bc6b7a3c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-headline</value>
      <webElementGuid>70c18051-3fd4-40e4-a7ce-627173e183e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Information regarding all applicants for this vacancy </value>
      <webElementGuid>9e23bb74-9895-4f44-9e46-2f756134fc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTabContent&quot;)/div[@id=&quot;search_candidates&quot;]/app-vacancies-search-candidates[@class=&quot;ng-star-inserted&quot;]/div[@id=&quot;search_candidates&quot;]/h2[@class=&quot;sub-headline&quot;]</value>
      <webElementGuid>035b70ff-031f-4c72-b7d7-53bde30870fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_candidates']/h2</value>
      <webElementGuid>d1f3bf67-ef95-4348-be99-f6a9a65fb94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='must know All'])[1]/following::h2[1]</value>
      <webElementGuid>d333b7fe-b4d5-457c-bc99-c80618b2d6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skill Sets'])[1]/following::h2[1]</value>
      <webElementGuid>49992d8a-c18a-4fd2-bc8e-50be8c54b8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Candidates'])[1]/preceding::h2[1]</value>
      <webElementGuid>2df8db4c-37cc-4fa8-959f-df3f70b17974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i. Location'])[1]/preceding::h2[1]</value>
      <webElementGuid>a25fc016-0c76-4c66-be31-05670b2a01bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Information regarding all applicants for this vacancy']/parent::*</value>
      <webElementGuid>847e5af3-3703-48af-ac35-52394b4e4f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-vacancies-search-candidates/div/h2</value>
      <webElementGuid>241731ca-744a-4d58-860b-de6f80fcd167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = ' Information regarding all applicants for this vacancy ' or . = ' Information regarding all applicants for this vacancy ')]</value>
      <webElementGuid>2ad229ec-278a-4f09-ae24-0b779fc451a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
