<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_i. Location_location</name>
   <tag></tag>
   <elementGuidId>a6f8e6d0-9b44-4f70-b822-d8207207ba7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='location'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.mb-2 > #location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07bd05cd-6f77-4764-a0d4-79040c187dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebed9028-b000-40a8-bc17-d5860938f3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>8e5f07ff-b309-4591-81c8-b02e2864f514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>6de5da54-5a03-4087-9de0-3fbe5908f52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input ng-pristine ng-valid ng-touched</value>
      <webElementGuid>908c71f0-092a-43b9-b4f5-3e50b1b2e62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTabContent&quot;)/div[@id=&quot;search_candidates&quot;]/app-vacancies-search-candidates[@class=&quot;ng-star-inserted&quot;]/div[@id=&quot;search_candidates&quot;]/div[@class=&quot;job-ab-content&quot;]/div[@id=&quot;accordionExample&quot;]/div[@class=&quot;accordion-item job-accordion border-0&quot;]/div[@id=&quot;collapseOne&quot;]/div[@class=&quot;accordion-body p-0 job-accordion-body&quot;]/div[@class=&quot;search-candidates-form py-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex mb-2&quot;]/input[@id=&quot;location&quot;]</value>
      <webElementGuid>d9b5ac91-238d-4e29-9acb-b4d4fba4f8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='location'])[2]</value>
      <webElementGuid>ef053e29-0323-40cb-81c0-812106a4c7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div/div/div/div/input</value>
      <webElementGuid>b834a332-a458-4069-b7b1-daccfe711a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/input</value>
      <webElementGuid>218d9302-ffe4-4b90-8fff-97a13c967255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'location' and @id = 'location']</value>
      <webElementGuid>cda4b3df-0830-493f-a48b-dd8b135aec9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
