<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_iii. Keyword_keyword</name>
   <tag></tag>
   <elementGuidId>20287ee1-68ed-45d2-b433-d5d5ae13f870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e75c4b50-86c0-46da-8820-b06a872a634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>310e1413-20cf-4249-baa6-0bb11875e164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>3dd0a45a-091e-44ac-ae87-f0421205b49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>fde3a6f8-0f3e-41de-b419-caffed307fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>5c6eb2cf-70a4-484a-b4c9-5ec5e5465565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword&quot;)</value>
      <webElementGuid>535342cd-94f3-4ee6-bf2c-a628d458a978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keyword']</value>
      <webElementGuid>68821d3f-e250-4b64-9b7d-1551f12bf377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div/div/div[3]/div/input</value>
      <webElementGuid>a6f23bf9-d5cf-4db2-bb00-de4c24d5c6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0ca5e6a1-3d28-4edf-9e35-6e284402618e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'keyword' and @id = 'keyword']</value>
      <webElementGuid>3ec41460-d377-43a5-99ef-198c4fc9091b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
