<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_29</name>
   <tag></tag>
   <elementGuidId>47b4c617-1681-4502-b72a-75b1dd948f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::td[33]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c8842ad1-c36e-4deb-9c15-1f209a210797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>available ng-star-inserted</value>
      <webElementGuid>8133a3eb-213a-4987-892d-54afcf27ece1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>d5b9df62-3edf-4065-902a-239ae97da833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-vacancies[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;job-managment-section&quot;]/div[@class=&quot;row gx-0&quot;]/div[@class=&quot;col-lg-4 vacancies-border-r&quot;]/div[@class=&quot;vacancies-content vh-height-height&quot;]/div[@class=&quot;vacancies-filter&quot;]/form[@class=&quot;ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;row gx-2&quot;]/div[@class=&quot;col-sm-5 col-12&quot;]/div[@class=&quot;filter-group&quot;]/ngx-daterangepicker-material[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;md-drppicker drops-down-auto ltr shown double&quot;]/div[@class=&quot;calendar left ng-star-inserted&quot;]/div[@class=&quot;calendar-table&quot;]/table[@class=&quot;table-condensed ng-star-inserted&quot;]/tbody[@class=&quot;drp-animate&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;available ng-star-inserted&quot;]</value>
      <webElementGuid>5ff4b95a-03c2-4831-9af3-701c36736e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::td[33]</value>
      <webElementGuid>b19d8db9-e360-48f3-a30c-60832f3fe19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::td[33]</value>
      <webElementGuid>4a6d125d-8b0e-42f4-83a7-4b768d7d1d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[2]/preceding::td[10]</value>
      <webElementGuid>c7df183c-f56c-4de6-8ce7-7b1aa1e25272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]</value>
      <webElementGuid>ece3f261-2424-49d0-891d-dec170883cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '29' or . = '29')]</value>
      <webElementGuid>2aa0dff1-f5a4-4ed4-8451-53fa428ff74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
