<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Interview Link_invitation_link</name>
   <tag></tag>
   <elementGuidId>cb0b8989-d00b-48e4-8324-23e6ce342799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invitation_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invitation_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07b36d7f-2154-4656-bedf-7da84d529b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c95cba5f-9f0e-40a9-8160-5470f4769f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>invitation_link</value>
      <webElementGuid>1d36fc39-c22a-4078-842c-6e0037ecf9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitation_link</value>
      <webElementGuid>3390974f-5da3-4b92-9052-9f8ffa9e31fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invitation_link</value>
      <webElementGuid>76ff58f3-e1d5-4b2d-9762-11dcfa40c040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-design bg-transparent rounded-0 font-18 ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>4e218c4c-72ac-4364-abea-9cb5fbd65f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitation_link&quot;)</value>
      <webElementGuid>207ef23c-d063-4fdf-b8a5-f1f418e11c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invitation_link']</value>
      <webElementGuid>bb5765fb-8416-4cab-bd4d-6b66899a6efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='applicants']/app-vacancies-applicants/div[2]/div/div/form/div/div[4]/div/input</value>
      <webElementGuid>0f74cd62-fef4-4f83-a317-963c57928876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>88d38901-3920-49cc-839f-acfe773f6424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'invitation_link' and @name = 'invitation_link']</value>
      <webElementGuid>0d2189c0-50c1-4613-b24a-f94151f159c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
