<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_X close pop up</name>
   <tag></tag>
   <elementGuidId>07b32a6c-ab7b-444f-9255-d5d510c2e51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notification_close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'notification_close' and (text() = ' X ' or . = ' X ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40474f16-0fd4-4d71-bbae-51318abfce03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification_close</value>
      <webElementGuid>805b8f93-b73d-4f1d-932e-8e674708659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-text</value>
      <webElementGuid>431e4568-ea61-48c3-aa10-be7c1ab6259f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> X </value>
      <webElementGuid>8b5071ff-3000-43e1-9db3-75645cdca180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_close&quot;)</value>
      <webElementGuid>a0fac4bf-69b1-4b3f-8024-cc758a3b686b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notification_close']</value>
      <webElementGuid>83932f6f-33ae-46f8-8ec7-fb3387a84072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='closed'])[1]/following::div[1]</value>
      <webElementGuid>0c7ec8f1-e0d3-417d-a867-848349274a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[3]</value>
      <webElementGuid>ccbb00cd-01e8-4ec7-baf2-8a28ff87a400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::div[3]</value>
      <webElementGuid>04bfdee8-4d58-4860-8fa4-10c66734a069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>82114711-b1e0-49f8-a8d9-8cdd1ac71f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>14538e48-720e-4cde-a2c0-b0711a7e8a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notification_close' and (text() = ' X ' or . = ' X ')]</value>
      <webElementGuid>a02e77a3-2537-4942-aec8-3c763c163a78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
