<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Time is required</name>
   <tag></tag>
   <elementGuidId>64f398c9-58cf-4923-badf-0953ee63def6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='applicants']/app-vacancies-applicants/div[2]/div/div/form/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>872edd1b-7897-4c19-a88e-264e3d6690bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>e2f9a92c-384a-4821-8a3c-a73d6007aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Time is required </value>
      <webElementGuid>ae341a1c-4c94-4c0a-8828-7e0790f0b889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicants&quot;)/app-vacancies-applicants[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;call-for-interview-section employe-modal ng-star-inserted&quot;]/div[@class=&quot;position-relative modal-overlay-custom&quot;]/div[@class=&quot;call-for-interview-box&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty ng-submitted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;mb-md-3 mb-2&quot;]/div[@class=&quot;text-danger ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>1a49b339-1a24-4741-93e5-be6e6018dafc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='applicants']/app-vacancies-applicants/div[2]/div/div/form/div/div[2]/div/div/div</value>
      <webElementGuid>195205bf-6ba9-4b27-b899-60574c2f3b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::div[2]</value>
      <webElementGuid>52344191-a8bb-400e-a9ff-3dda2463b6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date is required'])[1]/following::div[4]</value>
      <webElementGuid>15a7dc2f-d8d1-4a89-be90-0319e178b0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interview Type'])[1]/preceding::div[1]</value>
      <webElementGuid>f2416911-3c27-43ed-8176-de4b36b5b573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Interview'])[1]/preceding::div[1]</value>
      <webElementGuid>8ba319d0-3487-45f9-8bb8-871fbd4405d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time is required']/parent::*</value>
      <webElementGuid>b9dd7e70-fb7b-4f88-abb3-c51edad4b46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div</value>
      <webElementGuid>43f4010f-2cfe-402f-bc30-028305a8ecfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Time is required ' or . = ' Time is required ')]</value>
      <webElementGuid>92dec24d-379a-4591-82c9-f52c142d1c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
