<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_State Location</name>
   <tag></tag>
   <elementGuidId>bde744ae-beda-49c0-a3af-2dea511b9450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-97</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'mat-select-value-97' and (text() = 'State' or . = 'State')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37f7cea2-277c-46ef-b270-398a87e2d147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c49-52</value>
      <webElementGuid>d454fbe3-5bea-44c2-bf82-ec6f279e1e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-97</value>
      <webElementGuid>b2861145-ef78-48c7-a7d7-0983a77f0072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>93f9e293-5878-49ff-9947-f9ec5a1e20d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-97&quot;)</value>
      <webElementGuid>a18a7ff0-e7db-4767-b4d9-90159f0be2cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-97']</value>
      <webElementGuid>c5b759e7-26d4-4d3a-b0b8-afe971e944ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='state']/div/div</value>
      <webElementGuid>1eecf460-b260-4d55-8e6b-2d7705afd739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thailand'])[1]/following::div[6]</value>
      <webElementGuid>63781c02-e321-4dac-b0d5-76f8cf0948d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location*'])[1]/following::div[11]</value>
      <webElementGuid>bfa67fb9-b0ae-4742-93ce-c1de0f4c7239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::div[3]</value>
      <webElementGuid>db7a6ed5-2c3d-41cd-90c8-1bc8994c898f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-select/div/div</value>
      <webElementGuid>3d97e88d-0898-41f4-86a3-24d3609317e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-97' and (text() = 'State' or . = 'State')]</value>
      <webElementGuid>f6a50271-c456-4660-9f75-04cb3e075031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
