<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Position Number only</name>
   <tag></tag>
   <elementGuidId>b8ab955f-d151-4f56-bde4-979ae1cf47ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#position</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='position']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>034d929d-c768-416c-81ec-6aeeeae3241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fe1bf3d9-68b6-48f8-a812-181d90a2d4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>position</value>
      <webElementGuid>b298cc52-5f6f-4964-b0e2-50ac8dfd8766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3ef9c6b4-f338-4273-bfd5-ac2ccce8c57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return !((charCode > 31 &amp;&amp; (charCode &lt; 48 || charCode > 57)) &amp;&amp; charCode !== 46)</value>
      <webElementGuid>b4ec3a50-b470-437f-9ba6-076638689770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>position</value>
      <webElementGuid>e9b29002-2756-4807-a0b9-79685366909e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>position</value>
      <webElementGuid>87a33a0e-8e59-4188-9c21-e27562c7aaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control description-text ng-touched ng-dirty ng-valid</value>
      <webElementGuid>b682a017-f1ff-496c-9e6c-45b61dfca01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;position&quot;)</value>
      <webElementGuid>711430ff-50d6-4033-a3d8-3cec40d7208b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='position']</value>
      <webElementGuid>4eee231b-0c6b-4565-b73c-fa1c8e955b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>de1ad35a-52c3-4375-befa-7735af1e7b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'position' and @name = 'position']</value>
      <webElementGuid>b4d06cb4-871e-48b7-9b8c-f748a6619682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
