<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To salary_to_salary</name>
   <tag></tag>
   <elementGuidId>77ba5c57-5dda-4d56-a1c3-80672c7b1b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to_salary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to_salary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>234aa41f-5eb7-4a6b-bedf-1286ab572bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14c9e637-a9ee-4079-b6be-166e6a2f2f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+[.,]?[0-9]*</value>
      <webElementGuid>e3bcdaae-74ec-4d43-8a21-d34260f2cdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>to_salary</value>
      <webElementGuid>e1d137c2-b14a-4d93-b1c6-a11bb2013c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to_salary</value>
      <webElementGuid>b579c8f4-1f78-4f67-8a16-54c789762176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to_salary</value>
      <webElementGuid>774ac554-adfb-49ca-9e68-5232e78d26d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control description-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9d05fe48-7e50-4e6c-8864-88eb58a6cb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to_salary&quot;)</value>
      <webElementGuid>5379c128-3c4f-4c83-b08a-8c300515317a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to_salary']</value>
      <webElementGuid>87499400-0f1b-449f-aebd-5fc7fdf7c1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/input</value>
      <webElementGuid>ae02dee4-3fdc-434c-b462-674734caa3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'to_salary' and @name = 'to_salary']</value>
      <webElementGuid>15bde8c5-3c2f-414a-8705-fbc539764822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
