<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2 to 5 Years Experiences</name>
   <tag></tag>
   <elementGuidId>428ef52c-40a1-471c-93eb-023907cc5ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-277 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-277']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1516648e-5dc3-4c13-8911-8e5158b1174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>3e2b6e7d-99af-4ad1-bac1-bb69ea88d853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2 to 5 Years </value>
      <webElementGuid>db8a1e97-92c5-418f-bfbb-e4e06a5e2cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-277&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>ee1feb79-fdef-42ad-b915-f739074b872a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-277']/span</value>
      <webElementGuid>1541a342-3c1f-4f3e-bcbf-c364339acbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-option-277', '&quot;', ')/span[@class=', '&quot;', 'mat-option-text', '&quot;', ']')])[1]/following::span[2]</value>
      <webElementGuid>84452652-d3b6-4e62-9b32-7b83ead02a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[2]</value>
      <webElementGuid>6240d5e6-1563-4402-87df-7649e76ff65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2 to 5 Years']/parent::*</value>
      <webElementGuid>eac6750e-95e3-48ec-b60c-e55c64cc82c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>ecb2f58c-ddc2-4256-897e-71a5d41de5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 2 to 5 Years ' or . = ' 2 to 5 Years ')]</value>
      <webElementGuid>3a824ce0-1ea8-4037-bcd9-681940c1170e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
